// Code generated by hand for the avatar-borders feature. Mirror of the
// mockery-generated style used by the rest of the package (see
// reaction_repository_mock.go). Future runs of `make create_mocks`
// will overwrite this file.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// StorageRepository is a mock type for the StorageRepository type
type StorageRepository struct {
	mock.Mock
}

// UploadFile provides a mock function with given fields: ctx, prefix, filename, content, contentType
func (_m *StorageRepository) UploadFile(ctx context.Context, prefix string, filename string, content io.Reader, contentType string) (string, error) {
	ret := _m.Called(ctx, prefix, filename, content, contentType)

	if len(ret) == 0 {
		panic("no return value specified for UploadFile")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, string) string); ok {
		r0 = rf(ctx, prefix, filename, content, contentType)
	} else {
		r0 = ret.String(0)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, io.Reader, string) error); ok {
		r1 = rf(ctx, prefix, filename, content, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteFile provides a mock function with given fields: ctx, key
func (_m *StorageRepository) DeleteFile(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPresignedUploadURL provides a mock function with given fields: ctx, key, contentType
func (_m *StorageRepository) GetPresignedUploadURL(ctx context.Context, key string, contentType string) (string, error) {
	ret := _m.Called(ctx, key, contentType)

	if len(ret) == 0 {
		panic("no return value specified for GetPresignedUploadURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, key, contentType)
	} else {
		r0 = ret.String(0)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, key, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPresignedPutURL provides a mock function with given fields: ctx, key, expiresInSeconds
func (_m *StorageRepository) GetPresignedPutURL(ctx context.Context, key string, expiresInSeconds int) (string, error) {
	ret := _m.Called(ctx, key, expiresInSeconds)

	if len(ret) == 0 {
		panic("no return value specified for GetPresignedPutURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, int) string); ok {
		r0 = rf(ctx, key, expiresInSeconds)
	} else {
		r0 = ret.String(0)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, key, expiresInSeconds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MoveObject provides a mock function with given fields: ctx, sourceKey, destinationKey
func (_m *StorageRepository) MoveObject(ctx context.Context, sourceKey string, destinationKey string) error {
	ret := _m.Called(ctx, sourceKey, destinationKey)

	if len(ret) == 0 {
		panic("no return value specified for MoveObject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, sourceKey, destinationKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DownloadFile provides a mock function with given fields: ctx, key, destPath
func (_m *StorageRepository) DownloadFile(ctx context.Context, key string, destPath string) error {
	ret := _m.Called(ctx, key, destPath)

	if len(ret) == 0 {
		panic("no return value specified for DownloadFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, key, destPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DownloadFileBytes provides a mock function with given fields: ctx, key
func (_m *StorageRepository) DownloadFileBytes(ctx context.Context, key string) ([]byte, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for DownloadFileBytes")
	}

	var r0 []byte
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AvatarVariantURL provides a mock function with given fields: ctx, userID, variant, version, ext
func (_m *StorageRepository) AvatarVariantURL(ctx context.Context, userID string, variant string, version int, ext string) string {
	ret := _m.Called(ctx, userID, variant, version, ext)

	if len(ret) == 0 {
		panic("no return value specified for AvatarVariantURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, string) string); ok {
		r0 = rf(ctx, userID, variant, version, ext)
	} else {
		r0 = ret.String(0)
	}

	return r0
}

// UploadDirectory provides a mock function with given fields: ctx, localDir, remotePrefix
func (_m *StorageRepository) UploadDirectory(ctx context.Context, localDir string, remotePrefix string) (string, error) {
	ret := _m.Called(ctx, localDir, remotePrefix)

	if len(ret) == 0 {
		panic("no return value specified for UploadDirectory")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, localDir, remotePrefix)
	} else {
		r0 = ret.String(0)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, localDir, remotePrefix)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStorageRepository creates a new instance of StorageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageRepository {
	mock := &StorageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
