// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	domain "indagio-api/internal/domain"
)

// TokenService is an autogenerated mock type for the TokenService type.
type TokenService struct {
	mock.Mock
}

func (_m *TokenService) GenerateAccessToken(userID uuid.UUID, role domain.Role) (string, error) {
	ret := _m.Called(userID, role)
	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}
	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, domain.Role) (string, error)); ok {
		return rf(userID, role)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, domain.Role) string); ok {
		r0 = rf(userID, role)
	} else {
		r0 = ret.Get(0).(string)
	}
	if rf, ok := ret.Get(1).(func(uuid.UUID, domain.Role) error); ok {
		r1 = rf(userID, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (_m *TokenService) GenerateRefreshToken(userID uuid.UUID) (string, error) {
	ret := _m.Called(userID)
	if len(ret) == 0 {
		panic("no return value specified for GenerateRefreshToken")
	}
	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (string, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) string); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (_m *TokenService) ValidateAccessToken(token string) (*domain.TokenClaims, error) {
	ret := _m.Called(token)
	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}
	var r0 *domain.TokenClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.TokenClaims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.TokenClaims); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TokenClaims)
		}
	}
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (_m *TokenService) ValidateRefreshToken(token string) (*domain.TokenClaims, error) {
	ret := _m.Called(token)
	if len(ret) == 0 {
		panic("no return value specified for ValidateRefreshToken")
	}
	var r0 *domain.TokenClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.TokenClaims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.TokenClaims); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TokenClaims)
		}
	}
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func NewTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenService {
	mock := &TokenService{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
