// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "foro-unsaac-backend/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// BlockUser provides a mock function with given fields: ctx, id
func (_m *UserRepository) BlockUser(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for BlockUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, name, email, passwordHash
func (_m *UserRepository) Create(ctx context.Context, name string, email string, passwordHash string) (*domain.User, error) {
	ret := _m.Called(ctx, name, email, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*domain.User, error)); ok {
		return rf(ctx, name, email, passwordHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *domain.User); ok {
		r0 = rf(ctx, name, email, passwordHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, name, email, passwordHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByEmail provides a mock function with given fields: ctx, email
func (_m *UserRepository) FindByEmail(ctx context.Context, email string) (*domain.UserInternal, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *domain.UserInternal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.UserInternal, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.UserInternal); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserInternal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *UserRepository) FindByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAll provides a mock function with given fields: ctx, search, limit, offset
func (_m *UserRepository) ListAll(ctx context.Context, search string, limit int, offset int) ([]domain.User, int, error) {
	ret := _m.Called(ctx, search, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []domain.User
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]domain.User, int, error)); ok {
		return rf(ctx, search, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []domain.User); ok {
		r0 = rf(ctx, search, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = rf(ctx, search, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, search, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListAvailable provides a mock function with given fields: ctx, excludeUserID, search, limit, offset
func (_m *UserRepository) ListAvailable(ctx context.Context, excludeUserID uuid.UUID, search string, limit int, offset int) ([]domain.User, int, error) {
	ret := _m.Called(ctx, excludeUserID, search, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListAvailable")
	}

	var r0 []domain.User
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int, int) ([]domain.User, int, error)); ok {
		return rf(ctx, excludeUserID, search, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int, int) []domain.User); ok {
		r0 = rf(ctx, excludeUserID, search, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, int, int) int); ok {
		r1 = rf(ctx, excludeUserID, search, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, string, int, int) error); ok {
		r2 = rf(ctx, excludeUserID, search, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MarkVerified provides a mock function with given fields: ctx, email
func (_m *UserRepository) MarkVerified(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for MarkVerified")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateName provides a mock function with given fields: ctx, userID, name
func (_m *UserRepository) UpdateName(ctx context.Context, userID uuid.UUID, name string) error {
	ret := _m.Called(ctx, userID, name)

	if len(ret) == 0 {
		panic("no return value specified for UpdateName")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, userID, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePassword provides a mock function with given fields: ctx, email, passwordHash
func (_m *UserRepository) UpdatePassword(ctx context.Context, email string, passwordHash string) error {
	ret := _m.Called(ctx, email, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, email, passwordHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateAvatarURL provides a mock function with given fields: ctx, userID, avatarJSON
func (_m *UserRepository) UpdateAvatarURL(ctx context.Context, userID uuid.UUID, avatarJSON *string) (int, error) {
	ret := _m.Called(ctx, userID, avatarJSON)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAvatarURL")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string) int); ok {
		r0 = rf(ctx, userID, avatarJSON)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(int)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *string) error); ok {
		r1 = rf(ctx, userID, avatarJSON)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClearAvatar provides a mock function with given fields: ctx, userID
func (_m *UserRepository) ClearAvatar(ctx context.Context, userID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ClearAvatar")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(int)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateSelectedBorder provides a mock function with given fields: ctx, userID, borderID
func (_m *UserRepository) UpdateSelectedBorder(ctx context.Context, userID uuid.UUID, borderID *uuid.UUID) error {
	ret := _m.Called(ctx, userID, borderID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSelectedBorder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID) error); ok {
		r0 = rf(ctx, userID, borderID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
