@host = http://localhost:8080
@api = {{host}}/api

@name = Test User
@email = user@example.com
@password = StrongPassword123!
@otpCode = 491408
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODkyNjg3NjgsImlhdCI6MTc4OTAwOTU2OCwicm9sZSI6ImVzdHVkaWFudGUiLCJ1c2VyX2lkIjoiNzJlYmRjODEtZmRkMS00MjU5LThkZTctOTc0YjhhN2I1NzQ3In0.TGW-H3Mw7HOGUWqLwxWIBvACZgLL4BhvH-22fEcZ_QU

### Register user
POST {{api}}/auth/register
Content-Type: application/json

{
  "name": "{{name}}",
  "email": "{{email}}",
  "password": "{{password}}"
}

### Verify OTP
POST {{api}}/auth/verify-otp
Content-Type: application/json

{
  "email": "{{email}}",
  "code": "{{otpCode}}"
}

### Login user
POST {{api}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Get current user
GET {{api}}/auth/me
Authorization: Bearer {{accessToken}}

### Refresh token
POST {{api}}/auth/refresh

### Logout user
POST {{api}}/auth/logout
Authorization: Bearer {{accessToken}}

### Forgot password
POST {{api}}/auth/forgot-password
Content-Type: application/json

{
  "email": "{{email}}"
}

### Reset password
POST {{api}}/auth/reset-password
Content-Type: application/json

{
  "email": "{{email}}",
  "code": "{{otpCode}}",
  "new_password": "{{password}}"
}
