@host = http://localhost:8080
@api = {{host}}/api
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODkyNjg3NjgsImlhdCI6MTc4OTAwOTU2OCwicm9sZSI6ImVzdHVkaWFudGUiLCJ1c2VyX2lkIjoiNzJlYmRjODEtZmRkMS00MjU5LThkZTctOTc0YjhhN2I1NzQ3In0.TGW-H3Mw7HOGUWqLwxWIBvACZgLL4BhvH-22fEcZ_QU

@projectId = c2f086da-0d38-407d-9c9b-1b32d6d4ee8b

### Request export
POST {{api}}/projects/{{projectId}}/exports
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "format": "json",
  "options": {
    "include_media": true,
    "include_deleted": false
  }
}

### List exports for project
GET {{api}}/projects/{{projectId}}/exports
Authorization: Bearer {{accessToken}}
