@host = http://localhost:8080
@api = {{host}}/api
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3OTA1Mjc5MzUsImlhdCI6MTc5MDI2ODczNSwicm9sZSI6ImVzdHVkaWFudGUiLCJ1c2VyX2lkIjoiNzJlYmRjODEtZmRkMS00MjU5LThkZTctOTc0YjhhN2I1NzQ3In0.MumO0Jm7B58XI-SoisbCEtTbgn42TBbSHbBkxLlwyOE

@projectId = c2f086da-0d38-407d-9c9b-1b32d6d4ee8b
@instrumentId = ea35e4ec-499d-49da-a08e-a8758903870a
@questionnaireId = 9da241b4-c5d2-4e38-bc4f-ea3f1a8fb588

### Create instrument
POST {{api}}/projects/{{projectId}}/instruments
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Prueba onichan 1",
  "kind": "single_choice",
  "config": {
    "description": "Patient Health Questionnaire - 8 items",
    "response_labels": [
      "Ningún día",
      "Varios días",
      "Más de la mitad de los días",
      "Casi todos los días"
    ]
  }
}

### List instruments
GET {{api}}/projects/{{projectId}}/instruments
Authorization: Bearer {{accessToken}}

### Update instrument
PATCH {{api}}/projects/{{projectId}}/instruments/{{instrumentId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Customer satisfaction survey v2",
  "config": {
    "type": "object",
    "properties": {
      "question": { "type": "string" },
      "options": {
        "type": "array",
        "items": { "type": "string" }
      }
    },
    "required": ["question", "options"]
  },
  "status": "active"
}

### Create questionnaire
POST {{api}}/projects/{{projectId}}/questionnaires
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Baseline questionnaire",
  "schema": {
    "type": "object",
    "properties": {
      "age": { "type": "number" },
      "country": { "type": "string" }
    },
    "required": ["age"]
  }
}

### List questionnaires
GET {{api}}/projects/{{projectId}}/questionnaires
Authorization: Bearer {{accessToken}}

### Publish questionnaire
POST {{api}}/projects/{{projectId}}/questionnaires/{{questionnaireId}}/publish
Authorization: Bearer {{accessToken}}
