@host = http://localhost:8080
@api = {{host}}/api
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODkyNjg3NjgsImlhdCI6MTc4OTAwOTU2OCwicm9sZSI6ImVzdHVkaWFudGUiLCJ1c2VyX2lkIjoiNzJlYmRjODEtZmRkMS00MjU5LThkZTctOTc0YjhhN2I1NzQ3In0.TGW-H3Mw7HOGUWqLwxWIBvACZgLL4BhvH-22fEcZ_QU

@projectId = c2f086da-0d38-407d-9c9b-1b32d6d4ee8b
@memberEmail = 192666@unsaac.edu.peru

### Create project
POST {{api}}/projects
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Depresion, ansiedad y estrés | Proyecto de investigacion 2026-2027",
  "description": "Depresion, ansiedad y estrés | Proyecto de investigacion 2026-2027",
  "status": "active"
}

### List projects
GET {{api}}/projects
Authorization: Bearer {{accessToken}}

### Get project by id
GET {{api}}/projects/{{projectId}}
Authorization: Bearer {{accessToken}}

### Update project
PATCH {{api}}/projects/{{projectId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Customer Discovery v2",
  "description": "Updated project description.",
  "status": "active"
}

### Archive project
POST {{api}}/projects/{{projectId}}/archive
Authorization: Bearer {{accessToken}}

### Invite member to project
POST {{api}}/projects/{{projectId}}/members/invite
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "email": "{{memberEmail}}",
  "role": "member",
  "expires_at": "2026-12-31T23:59:59Z"
}

### List members
GET {{api}}/projects/{{projectId}}/members
Authorization: Bearer {{accessToken}}

### Delete project
DELETE {{api}}/projects/{{projectId}}
Authorization: Bearer {{accessToken}}
