@host = http://localhost:8080
@api = {{host}}/api
@accessToken = your_access_token_here

@userId = 11111111-1111-1111-1111-111111111111

### Public user profile
GET {{api}}/users/{{userId}}

### List available users
GET {{api}}/users/available?page=1&limit=20&q=ana
Authorization: Bearer {{accessToken}}

### Update user name
PATCH {{api}}/users/{{userId}}/name
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Updated User Name"
}
